.TH SSLSNIFF 1
.SH NAME
sslsniff \- program that analyzes TLS/SSL communication ISA_2020
.SH SYNOPSIS
.B ./sslsniff
[\fB\-r\fR <\fIFILE\fR>]
[\fB\-i\fR \fIINTERFACE\fR]
.SH DESCRIPTION
.LP 
.B<FILE>
-r switch for filename with pcapng file
.LP
.B<FILE>
-r switch for interface that the program can listen to
.SH OPTIONS
.TP
.BR \-r ", " "expects file name after this argument"
.LP
.BR \-i ", " "expexts interface name after this argument"